version: '3'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8082:8080"
    volumes:
      - ./openapi/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
      # API_URL: "http://localhost"

  swagger-api:
    image: danielgtaylor/apisprout
    ports:
      - "8083:8000"
    volumes:
      - ./openapi/openapi.yaml:/openapi.yaml
    command: /openapi.yaml
